services:
  ollama:
    volumes:
      - ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:${OLLAMA_DOCKER_TAG-latest}

  open-webui:
    build:
      context: .
      args:
        OLLAMA_BASE_URL: '/ollama'
      dockerfile: Dockerfile
    # image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    # ------------------------------- Choose Image -------------------------------
    # Choose an image for the OS you are using
    # ----------------------------------------------------------------------------
    # image: bmarcall/neuratech-open-webui:1.0        # MacOS image
    # image: bmarcall/neuratech-open-webui:1.1        # Linux image
    image: bmarcall/neuratech-open-webui:1.3          # Windows/Linux image
    # ------------------------------- Choose Image -------------------------------
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - ${OPEN_WEBUI_PORT-3000}:8080
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:11434'
      - 'WEBUI_SECRET_KEY='
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

volumes:
  ollama: {}
  open-webui: {}
